version: '3.9'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "StrongPassword@2024"
      DB_MYSQL_NAME: "npm"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - npm-db
      - nginx_ingress

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'StrongPassword@2024'
    volumes:
      - npm_db_data:/var/lib/mysql
    networks:
      - npm-db

volumes:
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local
  npm_db_data:
    driver: local

networks:
  npm-db:
    name: npm-db
    attachable: true
  nginx_ingress:
    name: nginx_ingress
    attachable: true
